Обработка ошибок
c2pc/go-musthave-metrics pull request #13
Opened 2024-11-10 16:14 UTC by c2pc

Добавлена обработка ошибок
Добавлены попытки соединения с сервером, БД, файлом

2024-11-13 17:30 UTC, bulbetski requested changes
Код на 4.7 из 5, надо поправить статусный коды и подумать, как обхединить дублирующиеся файлы. В остальном хорошо

2024-11-13 17:30 UTC, bulbetski commented on cmd/server/config/config.go
>  type Config struct {
Пакет конфиг, как на клиенте, так и в агенте стоит вынести в другой пакет. Например, internal/config. В cmd храним только наши main файлы

2024-11-13 17:30 UTC, bulbetski commented on cmd/server/config/config.go
>  		cfg.Restore = *restore
В нескольких местах в твоем конфиге разыменовывается указать без предварительной проверки на nil. Это потенциально может привести к панике. Стоит взять за правило всегда проверять на nil указатель перед его разыменованием.

2024-11-13 17:30 UTC, bulbetski commented on cmd/server/config/config.go
> +	databaseDSN     = flag.String("d", "", "The database DSN")
Совет
Использование flag.StringVar (и аналогичных методов, например, flag.IntVar, flag.BoolVar) позволяет сохранять значения флагов напрямую в переменные, без необходимости разыменования указателей и соответсвенно не придется проверять указатели на nil.

2024-11-13 17:30 UTC, bulbetski commented on cmd/server/config/config.go
>  func Parse() (*Config, error) {
на строчке 96 конфига надо исправить копипасту -- os.Getenv("ADDRESS")

```
	if envCfg.Restore != "" {
		cfg.Restore, err = strconv.ParseBool(envCfg.Restore)
		if err != nil {
			return nil, fmt.Errorf("failed to parse RESTORE: %s", err)
		}
	} else if v := os.Getenv("ADDRESS"); v != "" {
		cfg.Restore, err = strconv.ParseBool(v)
		if err != nil {
			return nil, fmt.Errorf("failed to parse RESTORE: %s", err)
		}
```

2024-11-13 17:30 UTC, bulbetski commented on cmd/server/main.go
>  		return
return избыточный. Fatal и так завершит выполнения программы

2024-11-13 17:30 UTC, bulbetski commented on cmd/server/main.go
>  		return
надо убрать return после каждого logger.Fatal

2024-11-13 17:30 UTC, bulbetski commented on internal/client/client.go
>  		Timeout: 1 * time.Second,
начение таймаута стоит вынести в конфигурацию или проще -- в константу

2024-11-13 17:30 UTC, bulbetski commented on internal/database/database.go
> +	return &DB{dsn: dsn}
В конструкторе `New` передается `dsn`, но не выполняется попытка установить соединение с базой данных. Рассмотри возможность сразу проверить `dsn`, чтобы заранее обнаружить какие-то проблемы.

Можно вообще в конструктор передавать conn -- это нормальная практика

2024-11-13 17:30 UTC, bulbetski commented on internal/database/database.go
> +	}
как будто бы пинг не должен открывать соединение с БД, он должен непосредственно пинговать. Надо разделять зону ответственности функций

2024-11-13 17:30 UTC, bulbetski commented on internal/database/database.go
> +package database
во всех методах проверяется соединение. Этого делать не нужно. Достаточно в мэйне создать соединение и пингануть бд. Методы должны выполнять свою основную функцию. Это хорошая практика, да и код дублироваться не будет

2024-11-13 17:30 UTC, bulbetski commented on internal/handler/handler.go
>  }
пинг стоит сделать в мэйне, а в хэндлере уже не париться по поводу наличия бд и коннекта

2024-11-13 17:30 UTC, bulbetski commented on internal/handler/handler.go
>  	}
доверим это всё нашей мэйн функции

2024-11-13 17:30 UTC, bulbetski commented on internal/handler/handler.go
>  			return
раз не удалось сохранить, то это уже ошибка сервера. StatusBadRequest, как и другие 4хх ошибки -- ошибки клиента. Серверные ошибки -- 5хх. В данном случае лучше возвращать InternalServerError

2024-11-13 17:30 UTC, bulbetski commented on internal/handler/handler.go
>  			return
стоит заменить код на InternalServerError

2024-11-13 17:30 UTC, bulbetski commented on internal/handler/handler.go
>  			c.JSON(http.StatusBadRequest, gin.H{"error": "Failed to set metric value"})
стоит заменить код на InternalServerError

2024-11-13 17:30 UTC, bulbetski commented on internal/handler/handler.go
>  			c.JSON(http.StatusBadRequest, gin.H{"error": "Failed to get metric value"})
Здесь как будто 404 ошибка

2024-11-13 17:30 UTC, bulbetski commented on internal/handler/handler.go
> +		switch metric.Type {
На get надо вернуть 404, на set 500

2024-11-13 17:30 UTC, bulbetski commented on internal/handler/handler.go
> +			c.JSON(http.StatusNotFound, gin.H{"error": "The metric id is empty"})
вот тут BadRequest

2024-11-13 17:30 UTC, bulbetski commented on internal/storage/counter.go
>  	defer s.mu.Unlock()
Тут досточно RLock(), т.к. производится только чтение

2024-11-13 17:30 UTC, bulbetski commented on internal/storage/counter.go
> +			[]time.Duration{1 * time.Second, 3 * time.Second, 5 * time.Second},
Рекомендуется избегать вложенных транзакций. `retry.Retry` здесь пытается повторить `ExecContext`, но не выполняет проверку состояния самой транзакции, что может вызвать неожиданные ошибки. Так же транзакции не должны виснуть надолго. Лучше вынести ретрай за пределы транзакции

2024-11-13 17:30 UTC, bulbetski commented on internal/storage/counter.go
> +		result[key] = value
Стоит добавить проверку для `rows.Err()`

2024-11-13 17:30 UTC, bulbetski commented on internal/storage/gauge.go
>  package storage
я так понимаю gauge.go дублирует counter.go. Надо их объединить. Если нет, исправь меня

2024-11-14 13:34 UTC, c2pc commented on internal/handler/handler.go
>  }
Интерфейс Pinger нужен для метода /ping, который проверяет соединение с БД

2024-11-14 13:44 UTC, c2pc commented on internal/handler/handler.go
>  			c.JSON(http.StatusBadRequest, gin.H{"error": "Failed to get metric value"})
Думаю тоже 500 ошибка, т.к. не может получить данные после сохранения

2024-11-14 14:52 UTC, c2pc commented on internal/storage/gauge.go
>  package storage
Gauge сохраняет значения - value = new.value
Сounter складывает - value = old.value + new.value

Поэтому было принято решение отделить их

2024-11-17 17:30 UTC, bulbetski commented on internal/storage/gauge.go
>  package storage
Различие одной строчки не стоит создания двух практически дублирующих друг друга файлов. Стоит подумать над тем, как объединить

2024-11-17 17:31 UTC, bulbetski commented on internal/storage/gauge.go
>  package storage
В целом, я работу приму, но ты подумай над исправлением, потому что потом это всё дело будет сложно модифицировать

2024-11-17 17:33 UTC, bulbetski commented
Исправил код хорошо, но остается открытым вопрос по поводу двух одинаковых файлов

2024-11-29 21:26 UTC, merged