Iter5
c2pc/go-musthave-metrics pull request #5
Opened 2024-09-27 16:12 UTC by c2pc

Выполнены задания согласно Инкременту 5

2024-09-30 14:45 UTC, rktkov requested changes

2024-09-30 14:45 UTC, rktkov commented on internal/storage/storage.go
> +type Storage[T Value] interface {
Давайте перенесем объявление этого интерфейса в место в коде (пакет), где он используется

2024-09-30 14:45 UTC, rktkov commented on internal/storage/storage.go
> +type Value interface {
Это очень похоже на объявление доменной сущности, поэтому его стоит перенести в другое место, например в пакет metric

2024-09-30 14:45 UTC, rktkov commented on internal/storage/gauge.go
> +func NewGaugeStorage() *GaugeStorage {
А вот тут стоит сразу возвращать не ссылку на структуру, а сам интерфейс Storage

2024-09-30 14:45 UTC, rktkov commented on internal/storage/counter.go
> +func NewCounterStorage() *CounterStorage {
А вот тут стоит сразу возвращать не ссылку на структуру, а сам интерфейс Storage

2024-09-30 14:45 UTC, rktkov commented on internal/metric/metric.go
> +type Value interface {
Повторное объявление интерфейса, значит надо из storage его удалить, а не переносить

2024-09-30 14:45 UTC, rktkov commented on internal/metric/metric.go
> +type Metric[T Value] interface {
Тот же комментарий, интерфейсы объявляем в месте использования.
А еще в го любят называть интерфейсы отглагольными существительными, которые обозначают суть действий. Так что стоит этот интерфейс переименовать.

2024-09-30 14:45 UTC, rktkov commented on cmd/server/main.go
> +	"github.com/c2pc/go-musthave-metrics/cmd/server/config"
import

Возьмите в привычку сортировать импортируемые пакеты следующим образом:
1. пакеты стандартной библиотеки
2. внешние установленные пакеты
3. внутренние пакеты проекта

Для того, чтобы разные автоматические инструменты их не пересортировывали, разделяйте блоки пустой строкой.

см. комментарий про порядок импорта
https://stackoverflow.com/questions/24790175/when-is-the-init-function-run

2024-09-30 19:05 UTC, c2pc commented
Import

Расположил на первом месте стандартные библиотеки, затем внешние библиотеки и в конце библиотеки моего сервиса

2024-09-30 19:07 UTC, c2pc commented
Interface

Перенес интерфейс Storage в место использования - пакет handler
Перенес интерфейс Metric в место использования - agent
Переименовал Metric в MetricReader

2024-09-30 19:09 UTC, c2pc commented on internal/storage/gauge.go
> +func NewGaugeStorage() *GaugeStorage {
Если я пернес интерфейс Storage в handler, то мне нужно импортировать в storage пакет из handler?
Я решил оставить ссылку на структуру как есть

2024-10-01 09:04 UTC, rktkov requested changes

2024-10-01 09:04 UTC, rktkov commented on internal/client/client.go
> +type IClient interface {
В Го совсем не принято так называть интерфейсы. Можно назвать Updater. И опять его надо вынести в пакет, где используется, а не где реализовывается

2024-10-01 09:04 UTC, rktkov commented on internal/handler/handler.go
> +type Storage[T int64 | float64] interface {
Storager

2024-10-01 09:04 UTC, rktkov commented on internal/handler/handler_test.go
> +	"github.com/stretchr/testify/assert"
Перемещались импорты.

2024-10-01 09:04 UTC, rktkov commented on internal/metric/counter.go
> +func NewCounterMetric() *CounterMetric {
Лучше пусть возвращает интерфейс, который реализует.

2024-10-01 09:04 UTC, rktkov commented on internal/metric/gauge.go
> +func NewGaugeMetric() *GaugeMetric {
Лучше пусть возвращает интерфейс, который реализует.

2024-10-01 09:04 UTC, rktkov commented on internal/storage/gauge.go
> +func NewGaugeStorage() *GaugeStorage {
И это нормально, согласно принципам чистой архитектуры - нижние (вспомогательные) слои могут ссылаться на верхние (основные), но не наоборот. Поэтому стоит возвращать интерфейс.

2024-10-03 13:47 UTC, c2pc commented
Вынес логику из agent/main.go в пакет reporter
Добавил контекст с отменой по времени для выхода из сервиса сборки метрик
Также добавил прослушку signal.Notify для принудительного выхода из сервиса сборки
Исправил импорт пакетов
Исправил интерфейсы

2024-10-03 15:17 UTC, rktkov approved these changes
Остался один не значительный комментарий, его можно к следующему ревью поправить.

2024-10-03 15:17 UTC, rktkov commented on internal/client/client.go
> +	"github.com/c2pc/go-musthave-metrics/internal/reporter"
Вот тут опять смешались импорты.

2024-10-04 05:24 UTC, merged